### ISSUE TITLE
Doesn't Extract Posts

### ISSUE THREAD

**Issue by cinsch** [Mirisong/facebook-admin-tool#20]
After going to the sold posts page, when I click on Extract Posts, nothing happens.  Firefox 50.1.0

**Comment by Mirisong** [comment]
Hi, sorry for the really long response time. I've had a lot on my plate with school lately. I've got bad news and good news.

### Bad news:
I've decided to retire this add-on since Firefox is dropping support for stuff it depends on, so there won't be a fix coming.

### Good news
I just finished the first version of the [Facebook Bot](https://github.com/Mirisong/Facebook-Bot), which does essentially the same thing and doesn't depend on anything Firefox is dropping support for. I tested it out and it seems to be working fine on Facebook's latest update (or the version they're giving me, anyway). It's currently waiting for review by Mozilla and should be available in a few days.

Please give it a try when it's ready, and if it doesn't work for you, file a bug on the new project and I'll see if I can figure out what's wrong.

Thanks for using my add-on and caring enough to let me know when it broke. =)

**Comment by Mirisong** [comment]
# Update

I misunderstood what has to happen to use Web-Extensions. It doesn't need to be a new add-on after all, so I can copy and tweak the code back into this one and continue updating the admin tool instead of the bot.

You won't need the Facebook Bot if you're willing to wait an extra day for review. Sorry for the confusion.
